### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ItsElectra** [MarquesCoding/Quintessential-Quintuplets-Switch-Translation#1]
How is this patch applied? I'm using Yuzu emulator with an NSP version of the game.

**Comment by MarquesCoding** [comment]
The game isn't translated yet.

**Comment by MarquesCoding** [comment]
https://www.reddit.com/r/5ToubunNoHanayome/comments/rvhwn0/translators_needed_nintendo_switch_the/
